"use client";

import { useCallback, useMemo } from "react";
import type { AnalysisResponse, FollowupResponse } from "@/lib/schema";

interface CopyReflectionProps {
  decision: string;
  reasons: string;
  analysis: AnalysisResponse;
  followup?: FollowupResponse | null;
}

export default function CopyReflection({ decision, reasons, analysis, followup }: CopyReflectionProps) {
  const fullText = useMemo(() => {
    const lines: string[] = [
      "── Blind Spot Reflection ──",
      "",
      "MY DECISION:",
      decision,
      "",
      "MY REASONS:",
      reasons,
      "",
      "── What I'm focusing on ──",
      ...analysis.visible_factors.map((f) => `• ${f}`),
      "",
      "── Assumptions ──",
      ...analysis.assumptions.map(
        (a) =>
          `• ${a.text}\n  Evidence: "${a.evidence}"\n  Why it matters: ${a.why_it_matters}\n  How to test: ${a.how_to_test}`
      ),
      "",
      "── Overlooked Factors ──",
      ...analysis.overlooked.map((o) => `• [${o.category}] ${o.text}\n  Evidence: "${o.evidence}"`),
      "",
      "── Conflicts in My Reasoning ──",
      ...analysis.conflicts.map((c) => `• ${c.text}\n  Evidence: "${c.evidence}"`),
      "",
      "── Questions to Consider ──",
      ...analysis.questions.map((q, i) => `${i + 1}. ${q}`),
    ];

    if (analysis.safety_note) {
      lines.push("", `Note: ${analysis.safety_note}`);
    }

    if (followup) {
      lines.push(
        "",
        "── Deeper Reflection ──",
        "",
        "Reasoning Summary:",
        followup.reasoning_summary,
        "",
        "Shifts:",
        ...followup.shifts.map((s) => `→ ${s}`),
        "",
        "Remaining considerations:",
        ...followup.remaining_blind_spots.map((s) => `• ${s}`)
      );
    }

    lines.push("", "──", "Generated by Blind Spot — the decision is always yours.");
    return lines.join("\n");
  }, [decision, reasons, analysis, followup]);

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(fullText);
    } catch {
      // Fallback for older browsers
      const textarea = document.createElement("textarea");
      textarea.value = fullText;
      textarea.style.position = "fixed";
      textarea.style.opacity = "0";
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
    }
  }, [fullText]);

  return (
    <button
      onClick={handleCopy}
      className="btn-secondary flex items-center gap-2"
      aria-label="Copy full reflection to clipboard"
    >
      <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor" aria-hidden="true">
        <path d="M4 4V1.5A1.5 1.5 0 015.5 0h9A1.5 1.5 0 0116 1.5v9a1.5 1.5 0 01-1.5 1.5H12v2.5a1.5 1.5 0 01-1.5 1.5h-9A1.5 1.5 0 010 14.5v-9A1.5 1.5 0 011.5 4H4zm1.5-2.5V4H10.5A1.5 1.5 0 0112 5.5V10.5h2.5V1.5H5.5zm-4 4v9h9v-9h-9z" />
      </svg>
      Copy reflection
    </button>
  );
}
